#!/usr/bin/env python3
"""Generate the town's Japanese voice lines with VOICEVOX.

Lines, speakers and delivery presets live in tools/voice/lines.json. The result is
public/voice/<id>.mp3 (loudness-normalised, 24 kHz mono MP3) plus
src/systems/voiceLines.js with subtitles, translations and durations.

Setup (VOICEVOX CORE 0.17, see https://github.com/VOICEVOX/voicevox_core):
  pip install voicevox_core-0.17.0-cp310-abi3-manylinux_2_34_x86_64.whl
  # plus the VOICEVOX ONNX Runtime build, the Open JTalk dictionary and the
  # VVM files 0.vvm (春日部つむぎ), 1.vvm (冥鳴ひまり), 2.vvm (九州そら)
  python tools/voice/generate.py --ort libvoicevox_onnxruntime.so.1.23.2 \
      --dict open_jtalk_dic_utf_8-1.11 --models models/

The generated audio must keep the credits listed in VOICE_CREDITS
("VOICEVOX:キャラ名"), as the voice library terms require.
"""
import argparse
import json
import subprocess
import tempfile
from pathlib import Path

from voicevox_core.blocking import Onnxruntime, OpenJtalk, Synthesizer, VoiceModelFile

ROOT = Path(__file__).resolve().parents[2]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ort', required=True, help='path to libvoicevox_onnxruntime.so')
    ap.add_argument('--dict', required=True, help='Open JTalk dictionary directory')
    ap.add_argument('--models', required=True, help='directory with the .vvm files')
    ap.add_argument('--only', nargs='*', help='line ids to (re)generate')
    args = ap.parse_args()

    cfg = json.loads((ROOT / 'tools/voice/lines.json').read_text())
    ort = Onnxruntime.load_once(filename=args.ort)
    syn = Synthesizer(ort, OpenJtalk(args.dict))
    for vvm in sorted(Path(args.models).glob('*.vvm')):
        with VoiceModelFile.open(vvm) as m:
            syn.load_voice_model(m)

    out_dir = ROOT / 'public/voice'
    out_dir.mkdir(parents=True, exist_ok=True)
    meta = {}
    for ln in cfg['lines']:
        lid = ln['id']
        voice = cfg['voices'][ln['voice']]
        preset = cfg['presets'][ln['preset']]
        mp3 = out_dir / f'{lid}.mp3'
        if not args.only or lid in args.only:
            style = voice['style']
            if ln.get('kana'):
                q = syn.create_audio_query_from_kana(ln['kana'], style)
            else:
                q = syn.create_audio_query(ln.get('say', ln['ja']), style)
            q.speed_scale = preset['speed']
            q.intonation_scale = preset['intonation']
            q.pitch_scale = preset.get('pitch', 0.0)
            q.pre_phoneme_length = 0.12
            q.post_phoneme_length = 0.25
            # pauses at 、/。: the model predicts 0.8-1.8 s, which drags; scale them by the
            # preset and cap them (announcements breathe a little more than a clerk)
            k, cap = preset.get('pause', 1.0), preset.get('pauseMax', 0.45)
            for ph in q.accent_phrases:
                pm = ph.pause_mora
                if isinstance(pm, dict):
                    pm['vowel_length'] = min(pm['vowel_length'] * k, cap)
                elif pm is not None:
                    pm.vowel_length = min(pm.vowel_length * k, cap)
            wav = syn.synthesis(q, style)
            with tempfile.NamedTemporaryFile(suffix='.wav') as tmp:
                tmp.write(wav)
                tmp.flush()
                subprocess.run([
                    'ffmpeg', '-v', 'error', '-y', '-i', tmp.name,
                    '-af', 'highpass=f=70,afade=t=in:d=0.02,areverse,afade=t=in:d=0.06,areverse,loudnorm=I=-17:TP=-1.5:LRA=11',
                    '-ar', '24000', '-ac', '1', '-c:a', 'libmp3lame', '-b:a', '48k', str(mp3),
                ], check=True)
            print(lid, q.kana)
        # duration from the encoded file
        dur = float(subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', str(mp3)],
                                   capture_output=True, text=True, check=True).stdout.strip())
        meta[lid] = {'who': ln['who'], 'ja': ln['ja'], 'zh': ln['zh'], 'voice': ln['voice'], 'dur': round(dur, 2)}

    credits = sorted({v['credit'] for v in cfg['voices'].values()})
    js = ['// Generated by tools/voice/generate.py from tools/voice/lines.json: do not edit by hand.',
          f'export const VOICE_CREDITS = {json.dumps(credits, ensure_ascii=False)};',
          'export const VOICE_LINES = {']
    for lid, m in meta.items():
        js.append(f'  {lid}: {json.dumps(m, ensure_ascii=False)},')
    js.append('};')
    (ROOT / 'src/systems/voiceLines.js').write_text('\n'.join(js) + '\n')
    print('wrote', len(meta), 'lines')


if __name__ == '__main__':
    main()
